package net.fugginbeenus.notchcurrency.net;

import net.fugginbeenus.notchcurrency.compat.Net;
import net.fugginbeenus.notchcurrency.core.NotchCurrency;
import net.minecraft.network.FriendlyByteBuf;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.ServerPlayer;

public final class NotchPackets {
    public static final ResourceLocation BALANCE_SYNC    = NotchCurrency.id("balance_sync");
    public static final ResourceLocation BALANCE_REQUEST = NotchCurrency.id("balance_request");
    public static final ResourceLocation TRADE_OPEN      = NotchCurrency.id("trade_open");
    public static final ResourceLocation TRADE_UPDATE    = NotchCurrency.id("trade_update");
    public static final ResourceLocation TRADE_CANCEL    = NotchCurrency.id("trade_cancel");
    public static final ResourceLocation TRADE_COMPLETE  = NotchCurrency.id("trade_complete");
    public static final ResourceLocation BID_REQUEST     = NotchCurrency.id("bid_request");
    public static final ResourceLocation AUCTION_CANCEL  = NotchCurrency.id("auction_cancel");
    public static final ResourceLocation AUCTION_LIST    = NotchCurrency.id("auction_list");
    public static final ResourceLocation RAFFLE_ADMIN_SAVE = NotchCurrency.id("raffle_admin_save");
    public static final ResourceLocation BOUNTY_ACTION = NotchCurrency.id("bounty_action");
    public static final ResourceLocation BOUNTY_ADMIN_SAVE = NotchCurrency.id("bounty_admin_save");
    public static final ResourceLocation LOAN_ACTION = NotchCurrency.id("loan_action");
    public static final ResourceLocation SLOTS_SPIN = NotchCurrency.id("slots_spin");
    public static final ResourceLocation COINFLIP_FLIP = NotchCurrency.id("coinflip_flip");
    public static final ResourceLocation NPC_EDITOR_OPEN = NotchCurrency.id("npc_editor_open");
    public static final ResourceLocation NPC_EDITOR_REOPEN = NotchCurrency.id("npc_editor_reopen");
    public static final ResourceLocation NPC_SET_ROLE = NotchCurrency.id("npc_set_role");
    public static final ResourceLocation NPC_SET_NAME = NotchCurrency.id("npc_set_name");
    public static final ResourceLocation NPC_SET_FAREWELL = NotchCurrency.id("npc_set_farewell");
    public static final ResourceLocation NPC_PICKUP = NotchCurrency.id("npc_pickup");
    public static final ResourceLocation NPC_DELETE = NotchCurrency.id("npc_delete");
    public static final ResourceLocation NPC_SET_APPEARANCE = NotchCurrency.id("npc_set_appearance");
    public static final ResourceLocation NPC_SET_BEHAVIOR = NotchCurrency.id("npc_set_behavior");
    public static final ResourceLocation NPC_SET_STATS = NotchCurrency.id("npc_set_stats");
    public static final ResourceLocation NPC_SET_ATTRS = NotchCurrency.id("npc_set_attrs");
    public static final ResourceLocation ENCHANTER_ACTION = NotchCurrency.id("enchanter_action");
    public static final ResourceLocation COSMETIC_BUY = NotchCurrency.id("cosmetic_buy");
    public static final ResourceLocation TRADE_OFFER_CREATE = NotchCurrency.id("trade_offer_create");
    public static final ResourceLocation TRADE_OFFER_ACTION = NotchCurrency.id("trade_offer_action");
    public static final ResourceLocation SHOP_MANAGE_ACTION = NotchCurrency.id("shop_manage_action");
    public static final ResourceLocation SHOP_EDIT_ACTION = NotchCurrency.id("shop_edit_action");
    public static final ResourceLocation NPC_PRESET = NotchCurrency.id("npc_preset");
    public static final ResourceLocation NPC_PRESET_LIST = NotchCurrency.id("npc_preset_list");
    public static final ResourceLocation NPC_SHARE = NotchCurrency.id("npc_share");
    public static final ResourceLocation NPC_SHARE_CODE = NotchCurrency.id("npc_share_code");
    public static final ResourceLocation NPC_EQUIP = NotchCurrency.id("npc_equip");
    public static final ResourceLocation NPC_PATROL = NotchCurrency.id("npc_patrol");
    public static final ResourceLocation NPC_SET_POSE = NotchCurrency.id("npc_set_pose");
    public static final ResourceLocation NPC_POSE_PART = NotchCurrency.id("npc_pose_part");
    public static final ResourceLocation NPC_TRANSFORM = NotchCurrency.id("npc_transform");
    public static final ResourceLocation BALLOON_CONFIG = NotchCurrency.id("balloon_config");
    public static final ResourceLocation BALLOON_CONFIG_SYNC = NotchCurrency.id("balloon_config_sync");
    public static final ResourceLocation NPC_MODEL_LIST = NotchCurrency.id("npc_model_list");
    public static final ResourceLocation NPC_MODEL_SEND = NotchCurrency.id("npc_model_send");
    public static final ResourceLocation NPC_MODEL_WANT = NotchCurrency.id("npc_model_want");
    public static final ResourceLocation NPC_MODEL_PUSH = NotchCurrency.id("npc_model_push");
    public static final ResourceLocation NPC_MODELS_RELOAD = NotchCurrency.id("npc_models_reload");
    public static final ResourceLocation NPC_SET_CLIP = NotchCurrency.id("npc_set_clip");
    public static final ResourceLocation NPC_SET_ANIM = NotchCurrency.id("npc_set_anim");
    public static final ResourceLocation BOUNTY_TRACKER = NotchCurrency.id("bounty_tracker");
    public static final ResourceLocation CURRENCY_SYNC = NotchCurrency.id("currency_sync");
    public static final ResourceLocation NPC_DIALOGUE_OPEN = NotchCurrency.id("npc_dialogue_open");
    public static final ResourceLocation NPC_DIALOGUE_CHOICE = NotchCurrency.id("npc_dialogue_choice");
    public static final ResourceLocation NPC_DIALOGUE_TEMPLATE = NotchCurrency.id("npc_dialogue_template");
    public static final ResourceLocation NPC_DIALOGUE_CLEAR = NotchCurrency.id("npc_dialogue_clear");
    public static final ResourceLocation NPC_STUDIO_OPEN = NotchCurrency.id("npc_studio_open");
    public static final ResourceLocation NPC_STUDIO_DATA = NotchCurrency.id("npc_studio_data");
    public static final ResourceLocation NPC_STUDIO_SAVE = NotchCurrency.id("npc_studio_save");
    public static final ResourceLocation NPC_DIALOGUE_MODE = NotchCurrency.id("npc_dialogue_mode");
    public static final ResourceLocation NPC_BILLBOARD = NotchCurrency.id("npc_billboard");
    public static final ResourceLocation NPC_FACTION_PICK = NotchCurrency.id("npc_faction_pick");
    public static final ResourceLocation NPC_FACTION_LIST = NotchCurrency.id("npc_faction_list");
    public static final ResourceLocation MAIL_RECIPIENTS = NotchCurrency.id("mail_recipients");
    public static final ResourceLocation MAIL_TAB = NotchCurrency.id("mail_tab");
    public static final ResourceLocation MAIL_POST_OPEN = NotchCurrency.id("mail_post_open");
    public static final ResourceLocation MAIL_AIM = NotchCurrency.id("mail_aim");
    public static final ResourceLocation MAIL_TRADE = NotchCurrency.id("mail_trade");
    public static final ResourceLocation MAIL_SEND = NotchCurrency.id("mail_send");
    public static final ResourceLocation MAIL_TAKE = NotchCurrency.id("mail_take");
    public static final ResourceLocation NPC_RECRUITER_OPEN = NotchCurrency.id("npc_recruiter_open");
    public static final ResourceLocation NPC_RECRUITER_ACTION = NotchCurrency.id("npc_recruiter_action");
    public static final ResourceLocation NPC_ACTIONS_OPEN = NotchCurrency.id("npc_actions_open");
    public static final ResourceLocation NPC_ACTIONS_DATA = NotchCurrency.id("npc_actions_data");
    public static final ResourceLocation NPC_ACTIONS_SAVE = NotchCurrency.id("npc_actions_save");
    public static final ResourceLocation NPC_SCHEDULE_OPEN = NotchCurrency.id("npc_schedule_open");
    public static final ResourceLocation NPC_SCHEDULE_DATA = NotchCurrency.id("npc_schedule_data");
    public static final ResourceLocation NPC_SCHEDULE_SAVE = NotchCurrency.id("npc_schedule_save");
    public static final ResourceLocation NPC_SCHEDULE_TOOL = NotchCurrency.id("npc_schedule_tool");
    public static final ResourceLocation QUEST_OPEN      = NotchCurrency.id("quest_open");
    public static final ResourceLocation QUEST_DATA      = NotchCurrency.id("quest_data");
    public static final ResourceLocation QUEST_SAVE      = NotchCurrency.id("quest_save");
    public static final ResourceLocation QUEST_LOG       = NotchCurrency.id("quest_log");
    public static final ResourceLocation QUEST_NAMES     = NotchCurrency.id("quest_names");
    public static final ResourceLocation QUEST_DESIGN    = NotchCurrency.id("quest_design");
    public static final ResourceLocation QUEST_DELETE    = NotchCurrency.id("quest_delete");
    public static final ResourceLocation QUEST_HAND_IN   = NotchCurrency.id("quest_hand_in");
    public static final ResourceLocation ANIM_LIST       = NotchCurrency.id("anim_list");
    public static final ResourceLocation ANIM_DESIGN     = NotchCurrency.id("anim_design");
    public static final ResourceLocation ANIM_OPEN       = NotchCurrency.id("anim_open");
    public static final ResourceLocation ANIM_DATA       = NotchCurrency.id("anim_data");
    public static final ResourceLocation ANIM_SAVE       = NotchCurrency.id("anim_save");
    public static final ResourceLocation ANIM_DELETE     = NotchCurrency.id("anim_delete");
    public static final ResourceLocation NPC_SET_IDLE_ANIM = NotchCurrency.id("npc_set_idle_anim");
    public static final ResourceLocation NPC_SET_FLAVOR = NotchCurrency.id("npc_set_flavor");
    public static final ResourceLocation WAYSTONE_FEE_SYNC = NotchCurrency.id("waystone_fee_sync");
    public static final ResourceLocation ATM_WITHDRAW    = NotchCurrency.id("atm_withdraw");
    public static final ResourceLocation SHOP_PURCHASE   = NotchCurrency.id("shop_purchase");
    public static final ResourceLocation SHOP_SELL       = NotchCurrency.id("shop_sell");
    public static final ResourceLocation NPC_LOOKS       = NotchCurrency.id("npc_looks");
    public static final ResourceLocation SHOP_WITHDRAW = NotchCurrency.id("shop_withdraw");

    private NotchPackets() {}

    public static void sendBalance(ServerPlayer sp, long value) {
        FriendlyByteBuf buf = net.fugginbeenus.notchcurrency.compat.Net.buf();
        buf.writeVarLong(value);
        Net.sendToClient(sp, BALANCE_SYNC, buf);
    }
}